title: "Browser Extension Guide"
description: A guide for building browser extensions

aux_links:
  "Starter code":
  - "https://github.com/weinshel/webextension-starter"

# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs